### ISSUE TITLE
mapviz not available running "sudo apt-get install ros-indigo-mapviz" for Ubuntu 14.04.2

### ISSUE THREAD

**Issue by jeremy-a-asi** [swri-robotics/mapviz#257]
How do I update my package list for mapviz on Ubuntu 14.04.2? I was expecting it to be available at the same server as the rest of ros-indigo.

**Comment by evenator** [comment]
Please see the note on the README:

>At this time, Mapviz is only available from OSRF's prerelease apt repository (ros-shadow-fixed). Until the repository is synced over to the main ROS repository, the recommended installation method is to compile Mapviz from source code.

As soon as someone at OSRF syncs the package repository, you'll be able to install mapviz normally with apt-get.
