### ISSUE TITLE
Frame not updating

### ISSUE THREAD

**Issue by Georacer** [swri-robotics/mapviz#266]
Hello,

I have successfully visualized a tf_frame and a robot image on mapviz.

However, the positions and path trail doesn't update unless I drag map display around.

Any idea on what could be going wrong?

Thanks.

**Comment by malban** [comment]
This is a bug in the tf plug-in.  The callback function in the plug-in isn't triggering a update to the canvas like it should.  When other data is being visualized the fact that the tf plugin isn't triggering an update isn't normally noticed.

I'll push a fix soon.

**Comment by Georacer** [comment]
Verified to update correctly.
Thanks!
