### ISSUE TITLE
Release 0.0.4 for Indigo

### ISSUE THREAD

**Issue by evenator** [swri-robotics/mapviz#275]
I left Indigo out of the last release cycle and only released Jade because the NavSat plugin was still untested. This release would include the LaserScan plugin and the NavSat plugin (and probably some other things.) I'm waiting on confirmation of #238.

**Comment by pjreed** [comment]
Just noting that it works in Indigo for me.

**Comment by evenator** [comment]
0.0.4 released to the OSRF build farm in 9a4b7a149bc2e00fb2fd43c197fadb2bec770d51
