### ISSUE TITLE
Add Support for DeleteAll Markers

### ISSUE THREAD

**Issue by evenator** [swri-robotics/mapviz#276]
The marker message recently added a new action type DELETEALL.

The constant is not available in [indigo](http://docs.ros.org/indigo/api/visualization_msgs/html/msg/Marker.html), only [jade](http://docs.ros.org/jade/api/visualization_msgs/html/msg/Marker.html) but there's nothing to stop us from implementing the feature in Indigo by hardcoding a 3.

I already implemented this in the hydro branch, and I've found it pretty handy.

**Comment by matt-attack** [comment]
@pjreed  is this resolved?

**Comment by matt-attack** [comment]
It appears this has not been. Need to add an else if statement around here checking for an action of 3, and then clearing all markers if you catch it.

https://github.com/swri-robotics/mapviz/blob/master/mapviz_plugins/src/marker_plugin.cpp#L336

**Comment by KindDragon** [comment]
Fixed in MR #609
