### ISSUE TITLE
Utilize ROS-I's Travis continuous integration (CI) scripts

### ISSUE THREAD

**Issue by shaun-edwards** [swri-robotics/mapviz#280]
ROS-I now has some pretty generic scrips for utilizing Travis CI: https://github.com/ros-industrial/industrial_ci.

Travis CI allows checks to be performed on any PR made against the repo, see [here](https://github.com/ros-industrial/siemens_experimental/pull/8).

If there is interest, I can submit a PR against this and other swri repos to utilize this capability.

**Comment by evenator** [comment]
@pjreed Have you seen this?

**Comment by pjreed** [comment]
Ah, I had missed this while I was on break.  This looks neat.

We use TeamCity for CI internally, but it would be handy to have something external that we can integrate with Github.  I'll look into this when I have the chance.

**Comment by malban** [comment]
Done
