### ISSUE TITLE
OpenGL blending is enabled but overwritten.

### ISSUE THREAD

**Issue by elliotjo** [swri-robotics/mapviz#325]
OpenGL blending (alpha channel support) is enabled by default (in MapCanvas::initializeGL) but was broken by the support for QPainter.  It seems like there is some bad interaction with the call to QPainter::beignNativePainting() in MapCanvas::paintEvent().  Placing a call to glEnable(GL_BLEND) after the line restores functionality in plugins, but before does not.  This is just a work-around however, we should find the actual problem in case other GL state variables are being overwritten.

**Comment by pjreed** [comment]
Are there any existing plugins in which this behavior can easily be demonstrated?

**Comment by pjreed** [comment]
I believe that alpha transparency not working in the costmap plugin is a side effect of this.
@jgassaway @nick-alton
