### ISSUE TITLE
Clearing Topic Name Causes Unhandled Exception Crash

### ISSUE THREAD

**Issue by evenator** [swri-robotics/mapviz#327]
If a plugin does not check if a topic name is blank before subscribing to it, it causes an error if more than one plugin is subscribed to the blank topic because ROS throws an exception that the topic types don't match. I encountered this bug when I cleared the topic name on an image plugin and then on a disparity plugin:

```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'ros::ConflictingSubscriptionException'
  what():  Tried to subscribe to a topic with the same name but different md5sum as a topic that was already subscribed [stereo_msgs/DisparityImage/04a177815f75271039fa21f16acad8c9 vs. sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743]
```

Plugins known to have this bug (check off when fixed):

- [ ] image
- [ ] disparity

**Comment by pjreed** [comment]
I've actually found several more plugins that don't have any protection against subscribing to an empty topic.  Might as well fix all of them at once.
