### ISSUE TITLE
MapQuest tiles not loading

### ISSUE THREAD

**Issue by gsenkowski** [swri-robotics/mapviz#342]
Occasionally some tiles are not loaded/displayed properly (see screenshot). While i understand that this is most likely a problem with MapQuest i think there should be a mechanism to retry at least a few times after some interval. A restart of mapviz/the tile_map plugin might sovle the problem for these tiles but missing tiles like this seem to be a common occurence and you can't rely on restarting until all tiles in your area are loaded.

![screenshot from 2016-04-21 11 39 09](https://cloud.githubusercontent.com/assets/18593801/14706861/851361be-07c1-11e6-85b6-e3f7b851caca.png)

**Comment by pjreed** [comment]
The "Reset Cache" button added in #403 should alleviate this a bit, since pushing that should make it reload all of the tiles... but it would definitely be nice for the `tile_map` plugin to track invalid tiles and periodically try to reload them.
