### ISSUE TITLE
Full support for MarkerArray

### ISSUE THREAD

**Issue by Georacer** [swri-robotics/mapviz#363]
Hello,

I noticed that even though MarkerArray messages are parsed, only one element is displayed on the map, which is overwritten on the next message.

Would it be easy to add proper support for marker arrays, i.e. have multiple marker icons appear and stay on the map at the same time?

**Comment by malban** [comment]
I think this works as expected as long as markers are given a unique ID/namespace.

**Comment by Georacer** [comment]
Yup,

Providing a unique ID did the trick and my screen fills with markers.

Things start halting to a crawl when millions of markers occupy the 
screen, but that's expected.

Thanks!
