### ISSUE TITLE
Cannot display Arrow marker

### ISSUE THREAD

**Issue by Georacer** [swri-robotics/mapviz#365]
Hello!

I have trouble visualizing an arrow marker.

I think I have initialized everything properly, but I can't get it to work, even though I get an OK message in the topic (**marker/attractor**) subscription from Mapviz.

You can see the topic content and the Mapviz window in the attached picture.
![screenshot from 2016-06-06 11 57 12](https://cloud.githubusercontent.com/assets/3149996/15816936/154c95bc-2bde-11e6-9a4c-23a29d7fce4d.png)

fcu is the same frame as the rover, basically the body frame.

If I swap the marker type to 1 (a cube) then it displays correctly, which is even weirder.

I have tried

- passing all-zero pose and a 2-long points array
- passing only pose data
- both simultaneously

Can you replicate my issue or does it work for you?

Thank you in advance.

**Comment by pjreed** [comment]
It looks as though support for the ARROW marker hasn't been implemented.  I'll work on that.

**Comment by Georacer** [comment]
Thanks! Much appreciated. At least this time it wasn't me falling short on the API ;)

**Comment by pjreed** [comment]
I've tentatively implemented support for arrows, although I don't have any bags with real data in them and am just using test data I've injected, so I might have missed some edge cases.  Feel free to try building my PR and see if they work for you.
