### ISSUE TITLE
Add a button to reset to the default zoom level and location

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/mapviz#371]
Sometimes after you've been panning around and zooming in and out for a while, you can lose track of where you are and it's hard to figure out how to get back to the origin.  I believe it's possible to do that right now by switching the target frame to something else and then back to your previous frame, but that's kind of a pain and not intuitive.  It'd be better to have a better somewhere that will reset your zoom level and location.

**Comment by NikolausDemmel** [comment]
Yeah this would be awesome. I got lost within the first minute of use while  of zooming out all the way looking in awe at the awesome tile_map plugin :-)
