### ISSUE TITLE
Cant load tiles from mapquest 

### ISSUE THREAD

**Issue by davidrotor** [swri-robotics/mapviz#402]
how can I load tiles from other sources if these are deprecated?
![mapviz_20160718t055419_227275](https://cloud.githubusercontent.com/assets/10190881/16906753/d7781592-4c79-11e6-9a19-f1f92efe633d.png)

**Comment by pjreed** [comment]
For what it's worth, the Stamen map sources listed in the `tile_map` tool still work, although they're a bit lower quality.

I'm also working on some modifications right now that will make it easier to add other map sources to the tool, and hopefully that'll be ready soon.

**Comment by davidrotor** [comment]
Ty ill use stamen map for now and wait for update!, how do I add a marker
to the map?

**Comment by pjreed** [comment]
To display markers on the map, you'll want to publish them on a ROS topic as a [visualization_msgs/Marker](http://docs.ros.org/api/visualization_msgs/html/msg/Marker.html) message and then add a `marker` plugin in Mapviz for that topic.

**Comment by davidrotor** [comment]
If i want to create markers from clicking in the map is it posible?

**Comment by pjreed** [comment]
Unfortunately, it's not currently possible to draw markers directly on the map.  It sure would be nice to have, though. :smile_cat: I'll add that to the list of things to do...
