### ISSUE TITLE
tile_map and multires_image not available after apt-get install ros-kinetic-mapviz-plugins 

### ISSUE THREAD

**Issue by danielsnider** [swri-robotics/mapviz#474]
The ubuntu 16.04 package `ros-kinetic-mapviz-plugins ` should install the `tile_map` and `multires_image` plugins.  However in my experience these plugins are not available after installing the plugin package, ie. `tile_map` and `multires_image` are not options when adding a new display to mapviz. 

As a work around I have to download the source from git and run `catkin_make`. It would be nicer (and time-saving) if apt-get would make the `tile_map` and `multires_image` plugins available.

**Comment by evenator** [comment]
`tile_map` and `multires_image` are in their own ROS packages, separate from the catch-all `mapviz_plugins` package. You should be able to install them like so:
```
sudo apt-get install ros-kinetic-tilemap ros-kinet-multires-image
```
