### ISSUE TITLE
[multires_image] Transparent Regions Rendered in Black

### ISSUE THREAD

**Issue by ramboto** [swri-robotics/mapviz#501]
Hello,
When I try to overlay an image on a tile map in mapviz, I notice the transparent regions of the image get colored black(I am using mapproxy with google map layer). If I put the same image on the google-earth application (with kml file), the transparent region is displayed correctly(I see the google map layer). Are there any ideas on how I can resolve this?

**Comment by pjreed** [comment]
Are you drawing the image with Mapviz's `image` plugin?  I suspect that alpha blending may not be enabled when it's drawing the image; we probably haven't tested it with images that have alpha channels.  I'll do that sometime when I have the time for it, unless somebody else gets there first...

**Comment by ramboto** [comment]
Ah sorry I think I wasn't specific in my description. I'm not using the Image plugin(sensor_msgs::Image), but the Multi-res Image plugin. I created a geo file giving the path to my image that I want to overlay onto a tile_map plugin. When I run mapviz and choose the multi-res image plugin, I see the image being overlaid correctly onto the tile_map plugin, but the transparent regions of my multi-res image turn out black.

If I use the same image on google earth the transparency is displayed correctly(or I can see the map layer underneath where the image is transparent)

**Comment by pjreed** [comment]
Ok, I took a look at this and was able to reproduce it, and I think it's because the `multires_image` plugin is internally storing GL textures without an alpha channel.  Should be easy to fix.

**Comment by omirbod** [comment]
Great thank you.
