### ISSUE TITLE
Suggestion: Image plugin "percent" should mean percent of original size

### ISSUE THREAD

**Issue by facontidavide** [swri-robotics/mapviz#542]
Hi,

I found the usability of the image "percent" option a little bit confusing.
In general, I expect the majority of the user to want the image ratio to be preserved.

I was preparing a PR to add a "Keep original image ratio" checkbox to the GUI, but the code is very hard to reason about because of the fact that "percent" is percent of the canvas.

Would you consider to change this to "percent of the original image size" ?

**Comment by facontidavide** [comment]
I guess it is a "no"

**Comment by malban** [comment]
I think the change is reasonable and would welcome a pull request.  It is unlikely that we will address the issue ourselves though.
