### ISSUE TITLE
Initial position and 2D goal buttons

### ISSUE THREAD

**Issue by facontidavide** [swri-robotics/mapviz#549]
Hi,

For my application, it would be very convenient to add these buttons that are available in RViz. 

![image](https://user-images.githubusercontent.com/2822888/33426229-66236b6c-d5c1-11e7-987a-7a87f7378fa7.png)

I can work on this and send a PR. My question is where do you think that they be added.

1) A separate plugin, not related to core application?
2) __statusbar__ on the bottom?
3) Actions in the __menubar__ on top?
4) __widget_2__ inside __configdock__?

Cheers

**Comment by malban** [comment]
It should definitely be a plug-in and not part of the core application.  For now, the best place for it would be like any of the other plug-ins.  In the future we may expand on the current plug-in architecture to provide access to more GUI elements like the menubar and statusbar.
