### ISSUE TITLE
Tile map plugin not showing map

### ISSUE THREAD

**Issue by pierbiag** [swri-robotics/mapviz#585]
Hello, every time I try to have the map shown, it starts throwing Network errors at me and it doesn't display the map:

[7f21621b5880] [/mapviz_ubuntu_6740_9181524986721827937/ImageCache::NetworkError:251]: NETWORK ERROR

The error is always 251.

I have working internet connection on the machine I'm using.

Any idea on how I could fix this?

Thanks,
Pier

**Comment by malban** [comment]
Can you upload the configuration file you are using?

**Comment by pierbiag** [comment]
I was about to reply to my own issue. Despite trying to debug the problem for a few days, only now I decided to copy and paste the config in #575 ... and it works ':-)

I still get the 251 errors, but many less and the map now appears.

**Comment by KindDragon** [comment]
Fixed in 1.1.0

**Comment by daniel-dsouza** [comment]
Looks like this is resolved.
