### ISSUE TITLE
Show custom marker on map

### ISSUE THREAD

**Issue by Adrianrr94** [swri-robotics/mapviz#620]
Hi,

I would like to add a custom marker like the blue car in the Readme's mapviz example.
![imagen](https://user-images.githubusercontent.com/36573289/54277291-c3417e80-458f-11e9-9fa1-163db91c6867.png)

Actually,what I want is exactly the same as the image, a drone's model following the obtained trayectory

I suppose that the blue car is a custom marker, so, how do I design a new visualization_msgs::Marker?

Thanks

**Comment by tynowell** [comment]
Hi Adrianrr94,

I think what you are looking for is the `robot_image` plugin. You can provide an image of a drone it'll follow the assigned frame.

**Comment by Adrianrr94** [comment]
Thanks Tyno, 

My fault, I read the readme but not carefully.

Thanks for your quick response.
