### ISSUE TITLE
Adding polygons to map - feature request?

### ISSUE THREAD

**Issue by tynowell** [swri-robotics/mapviz#621]
Hello,

I'm look for a way to add polygons to the map to show designated areas but I've noticed that there is only a plugin to manually draw in polygons, `draw_polygon`. I am currently reading polygons from a Shapefile and I would like to broadcast `geometry_msgs::PolygonStamped` to a topic from which mapviz can display them. Is there an existing feature that can do this? Or, would it be possible to modify `draw_polygon` to more of a `get_polygon`?

**Comment by daniel-dsouza** [comment]
One way I typically draw polygons is by publishing a marker array. You can use several makers with striped lines or a single, longer marker with a line list. The advantage to this approach is the ability to embed different types of makers, e.g. text, lines, polygons, in the same message/visualization.
