### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by ShawnSchaerer** [swri-robotics/mapviz#654]
Are there plans to support ROS2 in Mapviz?

**Comment by matt-attack** [comment]
Sadly yes.

**Comment by pjreed** [comment]
We've got some vague plans, but it is probably still a ways off in the future at this point.  Aside from being a significant undertaking in itself, we're still working our way through all of its dependencies; I'm actually working on porting [marti_common](https://github.com/swri-robotics/marti_common/pull/549) to ROS2 at the moment.

**Comment by ShawnSchaerer** [comment]
Thanks for the update.  We might be able to help with the port.

**Comment by pjreed** [comment]
We're now working on this in #672 .  Still got a ways to go, but the base mapviz package and several plugins have been ported.

**Comment by pjreed** [comment]
I forgot to close this issue out, but Mapviz has been released into ROS Dashing and Eloquent for a while now, and I just released it into Foxy.
