### ISSUE TITLE
Loading config file on startup

### ISSUE THREAD

**Issue by kledom** [swri-robotics/mapviz#661]
I just wanted to ask if mapviz provides a command line parameter (like -d in rviz) to directly open a configuration file when starting mapviz in roslaunch?

**Comment by malban** [comment]
a config file can be specified with the `config` ros parameter.

```
<launch>
  <node name="mapviz" type="mapviz" pkg="mapviz">
    <param name="config" value="<PATH TO CONFIG FILE"/>
  </node>
</launch>
```

or

```
rosrun mapviz mapviz _config:=<PATH_TO_CONFIG_FILE>
```
