### ISSUE TITLE
Cant Compile Master on Ros Melodic

### ISSUE THREAD

**Issue by geoeo** [swri-robotics/mapviz#708]
Hello,

I am getting a makefile error for the current master branch with ros melodic.

![error](https://user-images.githubusercontent.com/1128542/95871067-880bc080-0d6d-11eb-8cba-72562ea72b94.png)

I did not find a branch for melodic explicitly. Which version is sudo apt-get install ros-meldoic-mapviz built from? Since that works

**Comment by geoeo** [comment]
It seems to be related to multires_image. When I remove the folder I can compile it.
![boost_error](https://user-images.githubusercontent.com/1128542/95876533-73322b80-0d73-11eb-8951-61a436a72459.png)

**Comment by pjreed** [comment]
The `master` branch should build for every ROS1 distribution.

This error looks suspicious:
```
/usr/bin/ld: warning: libboost_filesystem.so.1.65.1, needed by /home/marc/ROS/MapViz/devel/lib/librqt_mapviz.so, may conflict with libboost_filesystem.so.1.72.0
```

Do you have a custom version of boost installed?  1.65 should be standard in Ubuntu 18.04.  My guess is that the system-installed version of yaml-cpp is trying to include headers from boost 1.72, but it's not compatible with them.

**Comment by geoeo** [comment]
I do under /usr/local. hmm didnt think that would be an issue. Thats annoying. thanks again

**Comment by pjreed** [comment]
I haven't tried it myself, but you might be able to work around that by passing a BOOST_ROOT variable pointing to the directory containing 1.65 as an argument to cmake; https://stackoverflow.com/questions/3016448/how-can-i-get-cmake-to-find-my-alternative-boost-installation has some information on that.

**Comment by geoeo** [comment]
wow thanks. Ill try that. I tried restricting the version in the CMake with find package but the yaml project doesnt seem to care. This seems better. Ill let you know. Thanks again!

**Comment by knickels** [comment]
I can confirm that master builds on 18.04 with boost 1.65, did it yesterday.

**Comment by geoeo** [comment]
Apparently this is an old issue with libyaml https://github.com/precice/openfoam-adapter/issues/18 
I couldnt get the whole repo to work, but plugins compile fine which is what I am interested id. 
Maybe fyi. I am trying to change the width/opacity of the path lines from the respective plugin. 
Would be cool to have that exposed in the gui
