### ISSUE TITLE
PoseArray

### ISSUE THREAD

**Issue by knickels** [swri-robotics/mapviz#714]
Is there a plugin for visualizing or entering a set of Poses?  For example, to interface with [https://wiki.ros.org/follow_waypoints](url) or a similar executive node?

**Comment by matt-attack** [comment]
Not currently. Feel free to add the capability to the Pose plugin though!
https://github.com/swri-robotics/mapviz/blob/master/mapviz_plugins/src/pose_plugin.cpp
