### ISSUE TITLE
where do node-specific plugins go?

### ISSUE THREAD

**Issue by knickels** [swri-robotics/mapviz#717]
I'm working on a plugin to control [http://wiki.ros.org/follow_waypoints](http://wiki.ros.org/follow_waypoints) from mapviz.

Was thinking of adding it to the `follow_waypoints` repo, but I'm thinking that this makes that repo now depend on mapviz, qt, and the like - lots of baggage.  Do y'all think that it would be appropriate to add it as a standalone package in this repo (similar to the way that multires_image and tile_map look in the codebase)?  

It's a bit more specialized than some plugins, though tbh not that different from `plan_route` :)

**Comment by danthony06** [comment]
Personally, I think it makes sense to put it in its own repo to avoid introducing unnecessary dependencies in Mapviz. I think your thoughts on keeping it out of the follow_waypoints repo are also spot on.
