### ISSUE TITLE
Allow building with C++14 for versions > ROS Kinetic

### ISSUE THREAD

**Issue by rjb0026** [swri-robotics/mapviz#720]
ROS Melodic and greater default builds to target C++14. I think all mapviz packages should default to those settings unless building for a version of ROS <= Kinetic, in which case builds should target C++11.

**Comment by matt-attack** [comment]
Is there a particular motivation for this since code will currently have to work with 11 anyways? ABI issues when using exterior libraries?

**Comment by rjb0026** [comment]
Just trying to get ahead of this pull request for a dependency (swri_yaml_util) https://github.com/swri-robotics/marti_common/pull/615

Some of the targets in mapviz that depend on that library were not targeting a modern version of c++ and causing a build failure in kinetic when while I was testing that pull request.
