### ISSUE TITLE
[GALACTIC] Binary packages for galactic

### ISSUE THREAD

**Issue by pepisg** [swri-robotics/mapviz#748]
Hi! Thanks for open sourcing this awesome package :). Are the binaries available for ROS Galactic? I tried to install them using apt (`ros-galactic-mapviz`) without success. Is there any ETA on when they will be released?
Thanks again!

**Comment by danthony06** [comment]
Sorry, we missed that one. I've bloomed the package, and you can track the progress here:
https://github.com/ros/rosdistro/pull/31528

**Comment by pepisg** [comment]
Thanks!
