### ISSUE TITLE
can not build mapviz

### ISSUE THREAD

**Issue by spcrobocar** [swri-robotics/mapviz#749]
When I build my workspace, it complained could not find rosapi. How can I fix it?

`-- +++ processing catkin package: 'mapviz'

-- ==> add_subdirectory(mapviz/mapviz)

-- Could NOT find rosapi (missing: rosapi_DIR)

-- Could not find the required component 'rosapi'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "rosapi" with any
`

**Comment by danthony06** [comment]
You can either manually install it via something like apt, with ```apt install ros-<your distro>-rosapi```, or use [rosdep](http://wiki.ros.org/rosdep) to install all of the package dependencies automatically. I would recommend using ```rosdep```.
