### ISSUE TITLE
ModuleNotFoundError: No module named 'rospkg'

### ISSUE THREAD

**Issue by byu-awesome-rover** [swri-robotics/mapviz#767]
I am running on ros melodic, and I am getting following error when I run mapviz.
```
Traceback (most recent call last):
  File "/home/marsrover/BYU-Mars-Rover/rover_ws/src/mapviz_tf/src/gps_to_mapviz.py", line 3, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
```
I tried "pip install rospkg", "sudo apt-get install rospkg".
Any suggestions?

**Comment by pjreed** [comment]
The `rospkg` Python module is provided by the `python-rospkg` Debian package (or `python3-rospkg` for ROS Noetic and later), so try `sudo apt install python-rospkg`.  In general, Debian packages for Python 2 modules are always prefixed with `python-`, and Python 3 modules are always prefixed with `python3-`.  (and using pip to install something should be a last resort, as globally-installed pip packages very often cause conflicts with packages installed by the OS's package manager)

It's pretty strange that you'd get that error in the first place, though, as that should be installed as part of a standard ROS desktop installation.  Have you sourced ROS in your terminal?  Can you run any other Python nodes successfully?

**Comment by byu-awesome-rover** [comment]
Hi @pjreed,
I tried to reinstall it using `sudo apt-get install python-rospkg`. But it says the package is the newest version on my machine. I even deleted `rospkg` from pip installed list and the error is still there.

**Comment by pjreed** [comment]
It seems very odd that you'd have an issue loading the `rospkg` Python module; it's not even necessary to source ROS since it's installed globally.  Is it possible you have a custom installation of Python that isn't reading from the global module path?

To diagnose it, try using `which python` to check the location of your `python` executable, then try running it interactively and see if you can `import rospkg`; for me, that looks like this:

```bash
root@08d3b85ec278:/# which python
/usr/bin/python

root@08d3b85ec278:/# python
Python 2.7.17 (default, Jul  1 2022, 15:56:32) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rospkg
>>> print(rospkg.__file__)
/usr/lib/python2.7/dist-packages/rospkg/__init__.pyc
>>>
```

**Comment by byu-awesome-rover** [comment]
Wait... I found the problem...
So, one of the file that I ran with the mapviz had `#!/usr/bin/env python3` instead of `#!/usr/bin/env python` which I think was expecting python3 version of rospkg when I am running on melodic which is based on python2.7. Thank you for your input and sorry that it was my fault.

**Comment by pjreed** [comment]
No problem, glad you figured it out!
