### ISSUE TITLE
WSL Crash on Startup [Process Died]

### ISSUE THREAD

**Issue by fullheartgames** [swri-robotics/mapviz#776]
I am trying to start this in WSL2 and am using ROS melodic. 

process[mapviz-1]: started with pid [24061]
process[initialize_origin-2]: started with pid [24062]
process[swri_transform-3]: started with pid [24063]
log4cxx: custom level class [ Debug level output from all nodes] not found.
log4cxx: custom level class [ Except mapviz] not found.
log4cxx: custom level class [ And TF] not found.
Warning: recursive print statement has occurred.  Throwing out recursive print.
log4cxx: custom level class [ Debug level output from all nodes] not found.
log4cxx: custom level class [ Except mapviz] not found.
log4cxx: custom level class [ And TF] not found.
Warning: recursive print statement has occurred.  Throwing out recursive print.
/opt/ros/melodic/lib/mapviz/mapviz: symbol lookup error: /opt/ros/melodic/lib/librqt_mapviz.so: undefined symbol: _ZN19swri_transform_util16TransformManagerC1EN5boost10shared_ptrIN2tf17TransformListenerEEE
[mapviz-1] process has died [pid 24061, exit code 127, cmd /opt/ros/melodic/lib/mapviz/mapviz __name:=mapviz __log:=/home/ron/.ros/log/9c496354-f8a7-11ed-b4c3-00155d7766b0/mapviz-1.log].
log file: /home/ron/.ros/log/9c496354-f8a7-11ed-b4c3-00155d7766b0/mapviz-1*.log
^C[swri_transform-3] killing on exit
[initialize_origin-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by danthony06** [comment]
We don't support WSL. It looks like you may have missing dependencies, but I'm not sure what else could be going on.
