### ISSUE TITLE
I can't get the mapviz

### ISSUE THREAD

**Issue by qfwysw** [swri-robotics/mapviz#786]
qf@qf-Lenovo-Legion-Y7000:~/program/my_test_folder/mapviz2$ sudo apt-get install ros-humble-mapviz
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-humble-mapviz

**Comment by danthony06** [comment]
We're currently dealing with problems with the ROS buildfarm not building Mapviz's dependencies correctly. I'm actively working on fixing the problems, and then Mapviz will be available as a binary.

**Comment by danthony06** [comment]
Release 3.6.1 of marti_common is released to the buildfarm and working normally. Binary versions of Mapviz will be available during the next sync by OSRF.
